image:
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - TOXENV: py39
      fast_finish: true
      PYTHON_V: "3.9"
      PYTHON: "C:\\Python39-x64"

stack: python %PYTHON_V%

install:
  - python --version
  - python -m pip install tox
  - python -m pip install -r requirements.txt
  - python -m pip install --upgrade build

build_script:
  - export PYTHONPATH=$(pwd)
  - python -m pip install .
  - python -m akmpt reverse tests/fixtures/beginner.kmp tmp.kmp

test_script:
  - python -m tox -e $TOXENV


for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%;
    - python --version
    - python -m pip install tox
    - python -m pip install -r requirements.txt
    - python -m pip install --upgrade build

  build_script:
    - SET PYTHONPATH=%CD%
    - python -m pip install .
    - python -m akmpt --help

  test_script:
    - python -m tox -e %TOXENV%
